### ISSUE TITLE
[QA] RestrictionTag

### ISSUE THREAD

**Issue by SnaiCrys** [DurtyFree/gta-v-data-dumps#12]
How to find out its own `RestrictionTag` from a specific `pedComponent NameHash`?

**Comment by DurtyFree** [comment]
Hi @SnaiCrys 
check out the ped component variation dump, it contains the restriction tags per name hash & component/drawable/texture combination: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/pedComponentVariations.json

But be aware drawable is currently wrong in this dump
