### ISSUE TITLE
Dump traffic lights

### ISSUE THREAD

**Issue by TheMysteriousVincent** [DurtyFree/gta-v-data-dumps#15]
The following object hashes are traffic lights and need to be dumped:

- `prop_traffic_01a` | `0x3E2B73A4`
- `prop_traffic_01b` | `0x336E5E2A`
- `prop_traffic_01d` | `0xD8EBA922`
- `prop_traffic_02a` | `0xD4729F50`
- `prop_traffic_02b` | `0x272244B2`
- `prop_traffic_03a` | `0x33986EAE`
- `prop_traffic_03b` | `0x2323CDC5`

Thanks in advance.

**Comment by DurtyFree** [comment]
Added with commit https://github.com/DurtyFree/gta-v-data-dumps/commit/4cf264f2bc36e2115d92fba39e1177229a71d5f1
enjoy.
