### ISSUE TITLE
Weapons (including components, paints, labels, damage information etc)

### ISSUE THREAD

**Issue by JanBlk** [DurtyFree/gta-v-data-dumps#17]
I love this data collection and i think it would be cool to have the weapons with its components, paints, labels, hashes, damage information and so on.

**Comment by DurtyFree** [comment]
Hi @T4styy thank you for the feedback, Weapons with their data is something I will definetely add in the future

**Comment by DurtyFree** [comment]
Is now available https://github.com/DurtyFree/gta-v-data-dumps/commit/2f188807b2c376597f62582321cc08fab396a3fe
