### ISSUE TITLE
Missing chairs/ from worldSeats (from DLC Casino & greater)

### ISSUE THREAD

**Issue by Ekinoxx0** [DurtyFree/gta-v-data-dumps#20]
Hello, it's seems you didn't update your worldSeats.json generator for the moment.

When you have time, please add these props to the generator :

ch_prop_casino_track_chair_01
ch_prop_casino_chair_01a
ch_prop_casino_chair_01b
ch_prop_casino_chair_01c
sum_mp_h_yacht_armchair_01
sum_mp_h_yacht_armchair_03
sum_mp_h_yacht_armchair_04
sum_mp_h_yacht_strip_chair_01
vw_prop_vw_offchair_01
vw_prop_vw_offchair_02
vw_prop_vw_offchair_03
vw_prop_casino_chair_01a
vw_prop_casino_track_chair_01
ch_chint02_worn_chairs
h4_int_04_arm_chair
h4_int_04_armchair_fireplace
h4_int_04_chair_chesterfield_01a
h4_int_04_desk_chair
h4_int_05_wood_chair_003
h4_int_05_wood_chair_1
h4_int_05_wood_chair_2
h4_int_05_wooden_chairs_2
h4_int_05_wooden_chairs_3
h4_prop_battle_club_chair_01
h4_prop_battle_club_chair_02
h4_prop_battle_club_chair_03
h4_prop_h4_chair_01a
h4_prop_h4_weed_chair_01a
h4_int_lev_sub_chair_01
h4_int_lev_sub_chair_02
h4_mp_h_yacht_armchair_01
h4_mp_h_yacht_armchair_03
h4_mp_h_yacht_armchair_04
h4_mp_h_yacht_strip_chair_01

sum_mp_h_yacht_sofa_01
sum_mp_h_yacht_sofa_02
ch_chint01_gamingr1_sofa
ch_chint02_03_sofa
ch_chint02_flat_sofa
ch_chint03_sofas
ch_chint07_foyer_sofa_004
ch_chint07_foyer_sofa_01
ch_chint07_foyer_sofa_03
h4_mp_h_yacht_sofa_01
h4_mp_h_yacht_sofa_02
vw_vwint01_gamingr1_sofa

h4_prop_h4_couch_01a

**Thanks for the great work :)**

**Comment by DurtyFree** [comment]
@Ekinoxx0 Thank you for enhancing the list of chair objects, I have updated my seats dump including all object locations of that list :)
