### ISSUE TITLE
request: pedOverlayCollections should include TxdName/Hash

### ISSUE THREAD

**Issue by aaronlink127** [DurtyFree/gta-v-data-dumps#39]
Getting the TXD from the OverlayName isn't always intuitive (i.e MP_LUXE_SN_007_M has the TXD MP_SN_005), this would make working with this data set easier. There's also TxtName, which I think is the actual texture name within the TXD, though I can't find a case where its different from TxdName.

**Comment by DurtyFree** [comment]
Hi there, this kind of data is very easily accessible on my website Pleb Masters: Forge.
As a supporter / patreon of pleb masters, you will be able to retrieve all file paths for various stuff easily, https://forge.plebmasters.de/decorations/NDIwODQxMTM1NA?search=MP_LUXE_SN_007_M
![grafik](https://user-images.githubusercontent.com/20757266/147855364-d17e2ddc-1c33-4329-b457-79d8963443ac.png)

As I dont want to inflate all my data dumps here with all this data, I am closing this here
