### ISSUE TITLE
vehicles.json mpsum2 DisplayName missing

### ISSUE THREAD

**Issue by MyHwu9508** [DurtyFree/gta-v-data-dumps#47]
Howdy,

for the new update the DisplayName of all mpsum2 vehicles are missing.
![image](https://user-images.githubusercontent.com/16681058/181340986-15741adb-990a-4fc5-a0e9-de5244804c5e.png)

Please assist.
Thank you <3

**Comment by egerdnc** [comment]
https://github.com/DurtyFree/gta-v-data-dumps/pull/48

**Comment by DurtyFree** [comment]
Thanks for reporting, I will take care of it in my data generator.

@egerdnc The data is automatically generated, thats why I can't accept PRs to fix them, I have to fix it in my data generator. But thanks for the efforts!

**Comment by DurtyFree** [comment]
Should be fixed with https://github.com/DurtyFree/gta-v-data-dumps/commit/dc1d06d5d62887b6b49c546b95dd666f65a7bf6c

thx for reporting
