### ISSUE TITLE
Vehicle class error

### ISSUE THREAD

**Issue by Ekinoxx0** [DurtyFree/gta-v-data-dumps#49]
Hi, it seems like the "Class" field in vehicles.json is different for the COMPACT class

COMPACTS is also used in the plural form where it should be COMPACT
(Class id could also be useful, they go from 0 to 22 and are used in some natives)

This is a very minor error, just letting you know
Thank for all the work you do 👍

**Comment by DurtyFree** [comment]
Hi there,

thanks for reporting! I have checked the data and it seems like R* themselves have defined this category wrong for some vehicles, just one more inconsistency in their data
I have fixed this in my dumper tool + added ClassId information.

https://github.com/DurtyFree/gta-v-data-dumps/commit/8ccffe1d7983dfb0a2046419e84702090f802f91
