### ISSUE TITLE
Object location dump of sat-dishes

### ISSUE THREAD

**Issue by Dav-Renz** [DurtyFree/gta-v-data-dumps#50]
Could you create a dump with the following sat-dishes?

Thanks a lot for your awesome work.

> prop_satdish_2_a
> prop_satdish_2_b
> prop_satdish_2_f
> prop_satdish_2_g
> prop_satdish_3_b
> prop_satdish_3_c
> prop_satdish_3_d
> prop_satdish_s_01
> prop_satdish_s_02
> prop_satdish_s_04a
> prop_satdish_s_04b
> prop_satdish_s_04c
> prop_satdish_l_01
> prop_satdish_l_02
> prop_satdish_l_02b
> prop_satdish_s_03
> prop_satdish_s_05a
> prop_satdish_s_05b
> bh1_03_satdish
> ch2_03_dishes001

**Comment by DurtyFree** [comment]
Hi there, thx for the idea.

Added it in https://github.com/DurtyFree/gta-v-data-dumps/commit/8430eb6a091d32ea778d75b2a34c9e74382ff480
