### ISSUE TITLE
objectslocations worldAntennas not complete

### ISSUE THREAD

**Issue by Dav-Renz** [DurtyFree/gta-v-data-dumps#51]
I think the following objects would be a good addition to the worldAntennas list.

> vb_34_baybuild_antenna
> sc1_23_antenna
> lr_cs6_04_antenna_d
> cs6_04_antenna
> cs4_10_antenna_d
> cs4_10_antenna
> ch2_03_radio_tower_01
> ch2_03_dishesdetail
> cs2_09b_tower01
> cs4_03_tower
> cs4_03_antnn
> ap1_01_a_aerialb
> cs3_07_toweraerials
> cs3_07_tower1_masts
> h4_mph4_wtowers_radiotowerdetail
> h4_mph4_wtowers_radiotower

**Comment by DurtyFree** [comment]
Hi there, thx for the contribution.

Added it in https://github.com/DurtyFree/gta-v-data-dumps/commit/8430eb6a091d32ea778d75b2a34c9e74382ff480
