### ISSUE TITLE
Backslashes in JSON

### ISSUE THREAD

**Issue by BerkieBb** [DurtyFree/gta-v-data-dumps#60]
The peds.json has backslashes in the json at the Russian translations, I'm not sure if it's at all of them but they cause a json error when I parse it in javascript
![image](https://user-images.githubusercontent.com/82737367/212917392-b28e2b60-052b-4400-880d-ead08e717f72.png)

**Comment by DurtyFree** [comment]
Oh i see, I will investigate this, thx for reporting!

**Comment by Sainan** [comment]
Although it's odd that some of the Russian labels here like `Ацтеки` are quoted, this is perfectly valid JSON.

I guess what you're trying to do is putting the JSON as a string in JavaScript and then calling JSON.parse on that string. Instead, you could do any of the following:
- Double-escape the quotes so the JSON data stays intact for the JSON.parse call
- Load the JSON data from a file so you don't need to double-escape it
- Accept that JSON is a subset of Javascript and don't use JSON.parse at all
  ![image](https://github.com/DurtyFree/gta-v-data-dumps/assets/63328889/4879cc91-6643-45e9-90eb-bb2172859524)

**Comment by DurtyFree** [comment]
Yes I have actually realize this too, as It would be very weird for some .NET library to just produce invalid JSON.

Thanks for pointing out @Sainan !

**Comment by BerkieBb** [comment]
> Although it's odd that some of the Russian labels here like `Ацтеки` are quoted, this is perfectly valid JSON.
> 
> I guess what you're trying to do is putting the JSON as a string in JavaScript and then calling JSON.parse on that string. Instead, you could do any of the following:
> 
> * Double-escape the quotes so the JSON data stays intact for the JSON.parse call
> * Load the JSON data from a file so you don't need to double-escape it
> * Accept that JSON is a subset of Javascript and don't use JSON.parse at all
>   ![image](https://user-images.githubusercontent.com/63328889/240619323-4879cc91-6643-45e9-90eb-bb2172859524.png)

Yes, I'm using JavaScript, didn't know that loading it from a file is a workaround for it, thanks!
