### ISSUE TITLE
Translated labels objects missing languages

### ISSUE THREAD

**Issue by Sainan** [DurtyFree/gta-v-data-dumps#61]
- Japanese
- Korean
- Portuguese
- Spanish (Mexican)

**Comment by DurtyFree** [comment]
Ye initially I didnt add those as I wasn't sure if they are needed/ people are interested in these. But I can add them for sure

**Comment by Sainan** [comment]
I'm interested in Japanese at least 🥹

**Comment by DurtyFree** [comment]
> I'm interested in Japanese at least, but don't see why not to just add all available data to a "data dumps" repo.

Nothing against adding it, will for sure add it.

**Comment by DurtyFree** [comment]
All missing languages should be available for all data dumps now, thanks for the request!
https://github.com/DurtyFree/gta-v-data-dumps/commit/f3459f41644b53943686db5e02e13ad605f76de1
