### ISSUE TITLE
RADIO_23_DLC_XM19_RADIO missing label

### ISSUE THREAD

**Issue by Sainan** [DurtyFree/gta-v-data-dumps#62]
`RADIO_23_DLC_XM19_RADIO` resolves to "iFruit Radio" in-game, but appears as null here: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/radioStations.json#L441-L453

**Comment by DurtyFree** [comment]
Weird, that translation seems to be part of some gxt2 that I don't load into my translation resolver, need to investigate this. Thanks!

**Comment by DurtyFree** [comment]
Fixed, thanks for reporting! https://github.com/DurtyFree/gta-v-data-dumps/commit/f3459f41644b53943686db5e02e13ad605f76de1

There was actually much more going wrong, so we got lots of other missing translations now:)
